---
title: "Who Needs Privacy? Exploring the relationship between personality and need for privacy"
subtitle: "Additional Analyses"
output:
  html_document:
    toc: TRUE
    toc_float:
      collapsed: FALSE
    toc_depth: 2
    code_folding: hide
bibliography      : 
  - "bibliography/r-references.bib"
  - "bibliography/references.bib"
  # pdf_document:
  #   toc: TRUE
---

```{r knitr-setup, include=F}
set.seed(170819)
knitr::opts_chunk$set(warning=F, echo=F, error=F, message=F, cache = T, 
                      tidy=T, dev = 'pdf', cache.extra = knitr::rand_seed)
options(digits = 3, width = 90)
```

```{r r-setup, include=F}
# install packages
# devtools::install_github("https://github.com/tdienlin/td")

# define packages
packages <- c("corrplot", "devtools", "GGally", "ggplot2", "haven", "kableExtra", "knitr", 
              "lavaan", "magrittr", "mice", "MVN", "PerFit", "psych", "quanteda.textstats",
              "pwr", "semPlot", "semTools", "tidyverse", "td")

# load packages
lapply(packages, library, character.only = TRUE)
```

Here you will be able to find additional analyses.
