---
title: "Who needs privacy?"
---

On this website, you can find the companion material for the paper _Who needs privacy? Exploring the relations between need for privacy and personality_. The paper published at the journal Collabra as registered report. The report is based on an [older paper](https://osf.io/m23bn) that was already submitted to Collabra but rejected. This paper now addressed the [feedback from the original submission](reviews.pdf) and considers the original paper a prestudy.

- You can either read the paper [in your browser](manuscript.html) or download it as [pdf](manuscript.pdf). 
- You can also read the [Stage 1 submission](proposal.html).
- The data are shared on [AUSSDA](https://data.aussda.at/citation?persistentId=doi:10.11587/IC66GC) and can be used for scientific purposes.

This website is produced directly from the project's [github repository](https://github.com/tdienlin/who_needs_privacy_rr). You can download the material, file an issue, or submit a pull request.

Please cite as follows:

Dienlin, T., & Metzger, M. (2024). Who Needs Privacy? Exploring the Relations Between Need for Privacy and Personality. _Collabra: Psychology_, 10(1), 120402. https://doi.org/10.1525/collabra.120402

